// <auto-generated />
using EindwerkCarParkingCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EindwerkCarParkingCore.Migrations
{
    [DbContext(typeof(EindwerkCarParkingContext))]
    [Migration("20180521223342_Identity")]
    partial class Identity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EindwerkCarParkingCore.Data.Entities.StoreUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Naam");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("Voornaam");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Eigenaar", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("EigenaarNaam")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.HasKey("Id");

                    b.ToTable("Eigenaars");
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Gemeente", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("GemeenteNaam")
                        .IsRequired();

                    b.Property<int>("LandId");

                    b.HasKey("Id");

                    b.HasIndex("LandId");

                    b.ToTable("Gemeentes");
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Land", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("LandNaam")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Lands");
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Locatie", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("GemeenteId");

                    b.Property<string>("Nr");

                    b.Property<string>("Straat")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("GemeenteId");

                    b.ToTable("Locaties");
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Parking", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("Bezet");

                    b.Property<int>("EigenaarId");

                    b.Property<int>("LocatieId");

                    b.Property<string>("ParkingNaam")
                        .IsRequired();

                    b.Property<int>("SoortId");

                    b.Property<int>("Totaal");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.HasIndex("LocatieId");

                    b.HasIndex("SoortId");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Soort", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("SoortNaam")
                        .IsRequired();

                    b.Property<int>("TotaalId");

                    b.HasKey("Id");

                    b.HasIndex("TotaalId");

                    b.ToTable("Soorts");
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Totaal", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("BezetteParkings");

                    b.Property<int>("MaxParkings");

                    b.HasKey("Id");

                    b.ToTable("Totaals");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Gemeente", b =>
                {
                    b.HasOne("EindwerkCarParkingLib.Land", "Land")
                        .WithMany("gemeente")
                        .HasForeignKey("LandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Locatie", b =>
                {
                    b.HasOne("EindwerkCarParkingLib.Gemeente", "Gemeente")
                        .WithMany("Locaties")
                        .HasForeignKey("GemeenteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Parking", b =>
                {
                    b.HasOne("EindwerkCarParkingLib.Eigenaar", "Eigenaar")
                        .WithMany("Parkings")
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EindwerkCarParkingLib.Locatie", "Locatie")
                        .WithMany("Parkings")
                        .HasForeignKey("LocatieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EindwerkCarParkingLib.Soort", "Soort")
                        .WithMany("Parkings")
                        .HasForeignKey("SoortId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EindwerkCarParkingLib.Soort", b =>
                {
                    b.HasOne("EindwerkCarParkingLib.Totaal", "Totaal")
                        .WithMany("Soorts")
                        .HasForeignKey("TotaalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EindwerkCarParkingCore.Data.Entities.StoreUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EindwerkCarParkingCore.Data.Entities.StoreUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EindwerkCarParkingCore.Data.Entities.StoreUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EindwerkCarParkingCore.Data.Entities.StoreUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
